const SUPPORTED_LANGUAGES = {
  en: { name: 'English', flag: '🇬🇧', nativeName: 'English' },
  es: { name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  fr: { name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  de: { name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  it: { name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  ja: { name: 'Japanese', flag: '🇯🇵', nativeName: '日本語' },
  zh: { name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
  pt: { name: 'Portuguese', flag: '🇧🇷', nativeName: 'Português' },
};

const FOOD_DICT = {
  es: { 'Starters':'Entrantes','Appetizers':'Aperitivos','Mains':'Platos Principales','Main Course':'Plato Principal','Desserts':'Postres','Drinks':'Bebidas','Beverages':'Bebidas','Salads':'Ensaladas','Soups':'Sopas','Sides':'Acompañamientos','Specials':'Especiales','Breakfast':'Desayuno','Lunch':'Almuerzo','Dinner':'Cena','Seafood':'Mariscos','Pasta':'Pasta','Pizza':'Pizza','Sushi':'Sushi','Burgers':'Hamburguesas','Sandwiches':'Sándwiches','Wine':'Vinos','Beer':'Cervezas','Cocktails':'Cócteles','Bruschetta':'Bruschetta','Soup of the Day':'Sopa del Día','Grilled Salmon':'Salmón a la Parrilla','Mushroom Risotto':'Risotto de Champiñones','Spicy Thai Curry':'Curry Tailandés Picante','Tiramisu':'Tiramisú','Chocolate Lava Cake':'Volcán de Chocolate','Caesar Salad':'Ensalada César','French Fries':'Papas Fritas','Grilled Chicken':'Pollo a la Parrilla','Margherita Pizza':'Pizza Margherita','Fish and Chips':'Pescado con Papas','Ice Cream':'Helado','Cheesecake':'Tarta de Queso','Pancakes':'Panqueques','Begin your meal right':'Comience su comida bien','Our signature dishes':'Nuestros platos insignia','Sweet endings':'Dulces finales','Toasted bread with fresh tomatoes, basil & olive oil':'Pan tostado con tomates frescos, albahaca y aceite de oliva',"Ask your server for today's selection":'Pregunte a su mesero por la selección del día','Atlantic salmon with lemon butter sauce & seasonal vegetables':'Salmón atlántico con salsa de mantequilla y limón y verduras de temporada','Creamy arborio rice with wild mushrooms & parmesan':'Arroz arborio cremoso con champiñones silvestres y parmesano','Red curry with coconut milk, vegetables & jasmine rice':'Curry rojo con leche de coco, verduras y arroz jazmín','Classic Italian coffee-flavored dessert':'Clásico postre italiano con sabor a café','Warm chocolate cake with a molten center':'Pastel de chocolate caliente con centro fundido'},
  fr: { 'Starters':'Entrées','Appetizers':'Amuse-bouches','Mains':'Plats Principaux','Main Course':'Plat Principal','Desserts':'Desserts','Drinks':'Boissons','Beverages':'Boissons','Salads':'Salades','Soups':'Soupes','Sides':'Accompagnements','Specials':'Spécialités','Breakfast':'Petit-déjeuner','Lunch':'Déjeuner','Dinner':'Dîner','Seafood':'Fruits de Mer','Pasta':'Pâtes','Wine':'Vins','Beer':'Bières','Bruschetta':'Bruschetta','Soup of the Day':'Soupe du Jour','Grilled Salmon':'Saumon Grillé','Mushroom Risotto':'Risotto aux Champignons','Spicy Thai Curry':'Curry Thaï Épicé','Tiramisu':'Tiramisu','Chocolate Lava Cake':'Moelleux au Chocolat','Caesar Salad':'Salade César','French Fries':'Frites','Grilled Chicken':'Poulet Grillé','Ice Cream':'Glace','Pancakes':'Crêpes','Begin your meal right':'Commencez bien votre repas','Our signature dishes':'Nos plats signatures','Sweet endings':'Douceurs finales','Toasted bread with fresh tomatoes, basil & olive oil':"Pain grillé avec tomates fraîches, basilic et huile d'olive","Ask your server for today's selection":'Demandez à votre serveur la sélection du jour','Atlantic salmon with lemon butter sauce & seasonal vegetables':'Saumon atlantique avec sauce beurre citron et légumes de saison','Creamy arborio rice with wild mushrooms & parmesan':'Riz arborio crémeux aux champignons sauvages et parmesan','Red curry with coconut milk, vegetables & jasmine rice':'Curry rouge au lait de coco, légumes et riz jasmin','Classic Italian coffee-flavored dessert':'Dessert italien classique au café','Warm chocolate cake with a molten center':'Gâteau au chocolat chaud au cœur fondant'},
  de: { 'Starters':'Vorspeisen','Appetizers':'Vorspeisen','Mains':'Hauptgerichte','Main Course':'Hauptgericht','Desserts':'Nachspeisen','Drinks':'Getränke','Beverages':'Getränke','Salads':'Salate','Soups':'Suppen','Sides':'Beilagen','Specials':'Spezialitäten','Breakfast':'Frühstück','Lunch':'Mittagessen','Dinner':'Abendessen','Seafood':'Meeresfrüchte','Pasta':'Pasta','Wine':'Weine','Beer':'Biere','Bruschetta':'Bruschetta','Soup of the Day':'Tagessuppe','Grilled Salmon':'Gegrillter Lachs','Mushroom Risotto':'Pilzrisotto','Spicy Thai Curry':'Scharfes Thai-Curry','Tiramisu':'Tiramisu','Chocolate Lava Cake':'Schokoladen-Lavakuchen','Caesar Salad':'Caesar Salat','French Fries':'Pommes Frites','Grilled Chicken':'Gegrilltes Hähnchen','Ice Cream':'Eiscreme','Cheesecake':'Käsekuchen','Pancakes':'Pfannkuchen','Begin your meal right':'Starten Sie Ihre Mahlzeit richtig','Our signature dishes':'Unsere Signature-Gerichte','Sweet endings':'Süße Abschlüsse','Toasted bread with fresh tomatoes, basil & olive oil':'Geröstetes Brot mit frischen Tomaten, Basilikum und Olivenöl',"Ask your server for today's selection":'Fragen Sie Ihren Kellner nach der Tagesauswahl','Atlantic salmon with lemon butter sauce & seasonal vegetables':'Atlantischer Lachs mit Zitronenbutter-Sauce und saisonalem Gemüse','Creamy arborio rice with wild mushrooms & parmesan':'Cremiger Arborio-Reis mit Wildpilzen und Parmesan','Red curry with coconut milk, vegetables & jasmine rice':'Rotes Curry mit Kokosmilch, Gemüse und Jasminreis','Classic Italian coffee-flavored dessert':'Klassisches italienisches Kaffee-Dessert','Warm chocolate cake with a molten center':'Warmer Schokoladenkuchen mit flüssigem Kern'},
  it: { 'Starters':'Antipasti','Appetizers':'Antipasti','Mains':'Primi e Secondi','Main Course':'Secondo Piatto','Desserts':'Dolci','Drinks':'Bevande','Beverages':'Bevande','Salads':'Insalate','Soups':'Zuppe','Sides':'Contorni','Specials':'Specialità','Breakfast':'Colazione','Lunch':'Pranzo','Dinner':'Cena','Seafood':'Frutti di Mare','Pasta':'Pasta','Wine':'Vini','Beer':'Birre','Bruschetta':'Bruschetta','Soup of the Day':'Zuppa del Giorno','Grilled Salmon':'Salmone alla Griglia','Mushroom Risotto':'Risotto ai Funghi','Spicy Thai Curry':'Curry Thai Piccante','Tiramisu':'Tiramisù','Chocolate Lava Cake':'Tortino al Cioccolato','Caesar Salad':'Insalata Caesar','French Fries':'Patatine Fritte','Grilled Chicken':'Pollo alla Griglia','Ice Cream':'Gelato','Pancakes':'Pancake','Begin your meal right':'Inizia bene il tuo pasto','Our signature dishes':'I nostri piatti forti','Sweet endings':'Dolci conclusioni','Toasted bread with fresh tomatoes, basil & olive oil':"Pane tostato con pomodori freschi, basilico e olio d'oliva","Ask your server for today's selection":'Chiedi al cameriere la selezione del giorno','Atlantic salmon with lemon butter sauce & seasonal vegetables':'Salmone atlantico con salsa al burro e limone e verdure di stagione','Creamy arborio rice with wild mushrooms & parmesan':'Riso arborio cremoso con funghi selvatici e parmigiano','Red curry with coconut milk, vegetables & jasmine rice':'Curry rosso con latte di cocco, verdure e riso jasmine','Classic Italian coffee-flavored dessert':'Classico dessert italiano al caffè','Warm chocolate cake with a molten center':'Tortino al cioccolato caldo con cuore fondente'},
  ja: { 'Starters':'前菜','Appetizers':'アペタイザー','Mains':'メイン料理','Main Course':'メインコース','Desserts':'デザート','Drinks':'ドリンク','Beverages':'飲み物','Salads':'サラダ','Soups':'スープ','Sides':'サイドメニュー','Specials':'スペシャル','Breakfast':'朝食','Lunch':'ランチ','Dinner':'ディナー','Seafood':'シーフード','Pasta':'パスタ','Pizza':'ピザ','Sushi':'寿司','Burgers':'バーガー','Sandwiches':'サンドイッチ','Wine':'ワイン','Beer':'ビール','Cocktails':'カクテル','Bruschetta':'ブルスケッタ','Soup of the Day':'本日のスープ','Grilled Salmon':'サーモンのグリル','Mushroom Risotto':'キノコのリゾット','Spicy Thai Curry':'スパイシータイカレー','Tiramisu':'ティラミス','Chocolate Lava Cake':'チョコレートラバケーキ','Caesar Salad':'シーザーサラダ','French Fries':'フライドポテト','Grilled Chicken':'グリルチキン','Ice Cream':'アイスクリーム','Cheesecake':'チーズケーキ','Pancakes':'パンケーキ','Begin your meal right':'お食事の始まりに','Our signature dishes':'自慢の料理','Sweet endings':'デザート','Toasted bread with fresh tomatoes, basil & olive oil':'フレッシュトマト、バジル、オリーブオイルのトーストブレッド',"Ask your server for today's selection":'本日のおすすめはスタッフにお尋ねください','Atlantic salmon with lemon butter sauce & seasonal vegetables':'アトランティックサーモンのレモンバターソース 季節の野菜添え','Creamy arborio rice with wild mushrooms & parmesan':'ワイルドマッシュルームとパルメザンのクリーミーリゾット','Red curry with coconut milk, vegetables & jasmine rice':'ココナッツミルクと野菜のレッドカレー ジャスミンライス添え','Classic Italian coffee-flavored dessert':'イタリア伝統のコーヒー風味デザート','Warm chocolate cake with a molten center':'とろけるチョコレートの温かいケーキ'},
  zh: { 'Starters':'开胃菜','Appetizers':'前菜','Mains':'主菜','Main Course':'主菜','Desserts':'甜点','Drinks':'饮品','Beverages':'饮料','Salads':'沙拉','Soups':'汤','Sides':'配菜','Specials':'特色菜','Breakfast':'早餐','Lunch':'午餐','Dinner':'晚餐','Seafood':'海鲜','Pasta':'意面','Pizza':'比萨','Sushi':'寿司','Burgers':'汉堡','Sandwiches':'三明治','Wine':'葡萄酒','Beer':'啤酒','Cocktails':'鸡尾酒','Bruschetta':'意式烤面包','Soup of the Day':'每日例汤','Grilled Salmon':'烤三文鱼','Mushroom Risotto':'蘑菇烩饭','Spicy Thai Curry':'泰式辣咖喱','Tiramisu':'提拉米苏','Chocolate Lava Cake':'熔岩巧克力蛋糕','Caesar Salad':'凯撒沙拉','French Fries':'薯条','Grilled Chicken':'烤鸡','Ice Cream':'冰淇淋','Cheesecake':'芝士蛋糕','Pancakes':'煎饼','Begin your meal right':'美味开始','Our signature dishes':'招牌菜','Sweet endings':'甜蜜收尾','Toasted bread with fresh tomatoes, basil & olive oil':'烤面包配新鲜番茄、罗勒和橄榄油',"Ask your server for today's selection":'请询问服务员今日精选','Atlantic salmon with lemon butter sauce & seasonal vegetables':'大西洋三文鱼配柠檬黄油酱和时令蔬菜','Creamy arborio rice with wild mushrooms & parmesan':'奶油野蘑菇帕玛森芝士烩饭','Red curry with coconut milk, vegetables & jasmine rice':'椰奶蔬菜红咖喱配茉莉花米饭','Classic Italian coffee-flavored dessert':'经典意大利咖啡风味甜点','Warm chocolate cake with a molten center':'温热熔岩巧克力蛋糕'},
  pt: { 'Starters':'Entradas','Appetizers':'Aperitivos','Mains':'Pratos Principais','Main Course':'Prato Principal','Desserts':'Sobremesas','Drinks':'Bebidas','Beverages':'Bebidas','Salads':'Saladas','Soups':'Sopas','Sides':'Acompanhamentos','Specials':'Especiais','Breakfast':'Café da Manhã','Lunch':'Almoço','Dinner':'Jantar','Seafood':'Frutos do Mar','Pasta':'Massas','Wine':'Vinhos','Beer':'Cervejas','Bruschetta':'Bruschetta','Soup of the Day':'Sopa do Dia','Grilled Salmon':'Salmão Grelhado','Mushroom Risotto':'Risoto de Cogumelos','Spicy Thai Curry':'Curry Tailandês Picante','Tiramisu':'Tiramisu','Chocolate Lava Cake':'Petit Gâteau de Chocolate','Caesar Salad':'Salada Caesar','French Fries':'Batatas Fritas','Grilled Chicken':'Frango Grelhado','Ice Cream':'Sorvete','Pancakes':'Panquecas','Begin your meal right':'Comece bem sua refeição','Our signature dishes':'Nossos pratos especiais','Sweet endings':'Doces finais','Toasted bread with fresh tomatoes, basil & olive oil':'Pão tostado com tomates frescos, manjericão e azeite',"Ask your server for today's selection":'Pergunte ao garçom a seleção do dia','Atlantic salmon with lemon butter sauce & seasonal vegetables':'Salmão atlântico com molho de manteiga e limão e legumes da estação','Creamy arborio rice with wild mushrooms & parmesan':'Arroz arbório cremoso com cogumelos selvagens e parmesão','Red curry with coconut milk, vegetables & jasmine rice':'Curry vermelho com leite de coco, legumes e arroz jasmim','Classic Italian coffee-flavored dessert':'Clássica sobremesa italiana com sabor de café','Warm chocolate cake with a molten center':'Bolo de chocolate quente com centro derretido'},
};

function translateText(text, lang) {
  if (!text || lang === 'en') return text;
  const dict = FOOD_DICT[lang];
  if (!dict) return text;
  if (dict[text]) return dict[text];
  const lower = text.toLowerCase();
  for (const [k, v] of Object.entries(dict)) {
    if (k.toLowerCase() === lower) return v;
  }
  return text;
}

module.exports = { SUPPORTED_LANGUAGES, FOOD_DICT, translateText };
